# Generated by Django 5.2.7 on 2025-10-31 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_documentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_names', to='master.documentcategory')),
            ],
        ),
    ]
