# Generated by Django 5.2.7 on 2025-11-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_documentcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
