# Generated by Django 5.2.7 on 2025-11-05 13:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_documentcategory_id_alter_documentname_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilIdName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('civil_id_name', models.CharField(max_length=255)),
                ('authority_full_name', models.CharField(max_length=255)),
                ('authority_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('VALID_UP_TO', 'Valid Up To')], max_length=20)),
                ('valid_duration_value', models.IntegerField(blank=True, null=True)),
                ('valid_duration_unit', models.CharField(blank=True, choices=[('MONTHS', 'Months'), ('YEARS', 'Years')], max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurposeOfVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='academicresulttype',
            old_name='Academicresulttype',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='educationlevelcode',
            old_name='level_code',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='maritalstatus',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='relation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studymainarea',
            old_name='Mainarea',
            new_name='name',
        ),
        migrations.AddField(
            model_name='country',
            name='currencyfullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currencyshortname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accreditationname',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accreditationname',
            name='valid_upto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_category', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_categories', to='master.paymentto')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='master.country')),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='master.documentcategory')),
                ('document_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='master.documentname')),
                ('visa_main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='master.visamain')),
                ('visa_major_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='master.visamajor')),
                ('visa_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='master.visaname')),
            ],
        ),
    ]
