# Generated by Django 5.2.7 on 2025-11-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_civilidname_paymentto_processtype_purposeofvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensename',
            name='short_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studyspecialisation',
            name='studyspecialisation',
            field=models.CharField(max_length=255),
        ),
    ]
