# Generated by Django 5.2.7 on 2025-11-12 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_licensename_short_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeAwardedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('degree_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeAwardedInstitute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ECAAwardingBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('selection_type', models.CharField(blank=True, choices=[('Student', 'Student'), ('Immigration', 'Immigration')], max_length=250, null=True)),
                ('valid_duration_value', models.IntegerField(blank=True, null=True)),
                ('eca_body_full_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('eca_body_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('eca_valid_period', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mediumofeducation',
            old_name='Perticulars',
            new_name='perticulars',
        ),
        migrations.RemoveField(
            model_name='accreditationname',
            name='valid_upto',
        ),
        migrations.RemoveField(
            model_name='licensename',
            name='valid_upto',
        ),
        migrations.AddField(
            model_name='accreditationname',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationname',
            name='valid_duration_unit',
            field=models.CharField(blank=True, choices=[('Months', 'Months'), ('Weeks', 'Weeks'), ('Years', 'Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accreditationname',
            name='valid_duration_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationname',
            name='valid_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Valid Upto', 'Valid Upto'), ('Date', 'Date')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='licensename',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensename',
            name='valid_duration_unit',
            field=models.CharField(blank=True, choices=[('Months', 'Months'), ('Weeks', 'Weeks'), ('Years', 'Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='licensename',
            name='valid_duration_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensename',
            name='valid_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Valid Upto', 'Valid Upto'), ('Date', 'Date')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='state',
            field=models.CharField(choices=[('STATE', 'State'), ('TERRITORY', 'Territory')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='Academicresult',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academicresulttype',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accreditationname',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accreditationname',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accreditationname',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='continents',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capitalCity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currencyCode',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='country',
            name='currencyfullname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currencyshortname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='fullName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='officialName',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='shortName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='countryName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.country'),
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='districtName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='district',
            name='stateName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.state'),
        ),
        migrations.AlterField(
            model_name='educationduration',
            name='durations',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='educationlevel',
            field=models.TextField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='educationType',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entrancetestname',
            name='fullname',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licensename',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licensename',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='licensename',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licensename',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediumofeducation',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownershiptype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relation',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representingcountry',
            name='continent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='representingcountry',
            name='currency_code',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='representingcountry',
            name='currency_short_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='representingcountry',
            name='short_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholdertype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='stateshortName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='studylanguagebanchmark',
            name='name',
            field=models.TextField(blank=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studymainarea',
            name='name',
            field=models.TextField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studymajorarea',
            name='majorarea',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studyspecialisation',
            name='studyspecialisation',
            field=models.TextField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timezone',
            name='Timezone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('districtName', 'stateName', 'countryName')},
        ),
        migrations.AlterUniqueTogether(
            name='ownershiptype',
            unique_together={('name', 'company_type')},
        ),
        migrations.AlterUniqueTogether(
            name='stakeholdertype',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='timezone',
            unique_together={('Timezone', 'countryName')},
        ),
        migrations.AddConstraint(
            model_name='accreditationname',
            constraint=models.UniqueConstraint(fields=('full_name', 'country', 'category'), name='unique_fullname_per_country_category'),
        ),
        migrations.AddConstraint(
            model_name='licensename',
            constraint=models.UniqueConstraint(fields=('full_name', 'country'), name='unique_fullname_per_country'),
        ),
        migrations.AddField(
            model_name='degreeawardedby',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_awarded_by_country', to='master.country'),
        ),
        migrations.AddField(
            model_name='degreeawardedby',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_awarded_by_education_level', to='master.educationlevel'),
        ),
        migrations.AddField(
            model_name='degreeawardedinstitute',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_by_instuite', to='master.country'),
        ),
        migrations.AddField(
            model_name='degreeawardedinstitute',
            name='degree_awarded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='master.degreeawardedby'),
        ),
        migrations.AddField(
            model_name='degreeawardedinstitute',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_by_education_level', to='master.educationlevel'),
        ),
        migrations.AddField(
            model_name='degreeawardedinstitute',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_by_state_instituite', to='master.state'),
        ),
        migrations.AddField(
            model_name='ecaawardingbody',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ECAAwarding_body', to='master.country'),
        ),
        migrations.AlterUniqueTogether(
            name='degreeawardedinstitute',
            unique_together={('degree_awarded_by', 'name')},
        ),
    ]
