# Generated by Django 5.2.7 on 2025-11-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_degreeawardedby_degreeawardedinstitute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicresult',
            name='Academicresult',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academicresulttype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
