# Generated by Django 5.2.7 on 2025-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_bankaccountfor_childrencanapplywithcandidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstatusname',
            name='process_status_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
