# Generated by Django 5.2.7 on 2025-11-21 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_academicresultgroup_agegroup_backlogsgroup_ecafor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='accreditationname',
            name='unique_fullname_per_country_category',
        ),
        migrations.AlterUniqueTogether(
            name='educationlevel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='accreditationname',
            name='country',
        ),
        migrations.RemoveField(
            model_name='childrenvisacategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spousevisacategory',
            name='name',
        ),
        migrations.AddField(
            model_name='childrenvisacategory',
            name='visamain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='childrenvisa', to='master.visamain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='civilidname',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='durations',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spousevisacategory',
            name='visamain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spousevisa', to='master.visamain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='Academicresult',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicresulttype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilidname',
            name='authority_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilidname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='civilidname',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='civilidname',
            name='valid_duration_unit',
            field=models.CharField(blank=True, choices=[('Months', 'Months'), ('Weeks', 'Weeks'), ('Years', 'Years')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='civilidname',
            name='valid_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Valid Upto', 'Valid Upto'), ('Date', 'Date')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clblevel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='educationlevel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='educationType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entrancetestmodulename',
            name='moduleName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entrancetestname',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entrancetestresult',
            name='testresult',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobprospect',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_prospect', to='master.representingcountry'),
        ),
        migrations.AlterField(
            model_name='jobprospect',
            name='occupationname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='languagetest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='languagetestmodulename',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occupationcategory',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_category', to='master.representingcountry'),
        ),
        migrations.AlterField(
            model_name='occupationcategory',
            name='occupationcategory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='occupationcategory',
            name='occupationcategorycode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='occupationcode',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_code', to='master.representingcountry'),
        ),
        migrations.AlterField(
            model_name='occupationcode',
            name='occupationcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='occupationlevel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_level', to='master.representingcountry'),
        ),
        migrations.AlterField(
            model_name='occupationlevel',
            name='occupationlevel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='occupationlevelcode',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_level_code', to='master.representingcountry'),
        ),
        migrations.AlterField(
            model_name='occupationlevelcode',
            name='occupationlevelcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='occupationname',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_name', to='master.representingcountry'),
        ),
        migrations.AlterField(
            model_name='occupationname',
            name='occupationname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='occupationversion',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_version', to='master.representingcountry'),
        ),
        migrations.AlterField(
            model_name='relatedoccupation',
            name='relatedoccupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studylanguagebanchmark',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studymainarea',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studymajorarea',
            name='majorarea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyspecialisation',
            name='studyspecialisation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='processsubstatusname',
            unique_together={('country', 'visa_main_category', 'process_status_name', 'process_sub_status_name')},
        ),
        migrations.AddConstraint(
            model_name='accreditationname',
            constraint=models.UniqueConstraint(fields=('full_name', 'category'), name='unique_fullname_per_country_category'),
        ),
        migrations.AddField(
            model_name='designation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='master.representingcountry'),
        ),
        migrations.AddField(
            model_name='designation',
            name='occupationcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='master.occupationcode'),
        ),
        migrations.AddField(
            model_name='designation',
            name='occupationname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='master.occupationname'),
        ),
        migrations.AddField(
            model_name='designation',
            name='occupationversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='master.occupationversion'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('occupationname', 'country', 'occupationversion', 'occupationcode', 'designation')},
        ),
    ]
