export const FACTOR_FOR_LIST = "FACTOR_FOR_LIST";
export const ADD_FACTOR_FOR = "ADD_FACTOR_FOR";
export const EDIT_FACTOR_FOR = "EDIT_FACTOR_FOR";
export const DELETE_FACTOR_FOR = "DELETE_FACTOR_FOR";
export const EXPORT_FACTOR_FOR = "EXPORT_FACTOR_FOR";
export const IMPORT_FACTOR_FOR = "IMPORT_FACTOR_FOR";

export const AGE_GROUP_LIST = "AGE_GROUP_LIST";
export const ADD_AGE_GROUP = "ADD_AGE_GROUP";
export const EDIT_AGE_GROUP = "EDIT_AGE_GROUP";
export const DELETE_AGE_GROUP = "DELETE_AGE_GROUP";
export const EXPORT_AGE_GROUP = "EXPORT_AGE_GROUP";
export const IMPORT_AGE_GROUP = "IMPORT_AGE_GROUP";
