export const FACTOR_FOR_LIST = "FACTOR_FOR_LIST";
export const ADD_FACTOR_FOR = "ADD_FACTOR_FOR";
export const EDIT_FACTOR_FOR = "EDIT_FACTOR_FOR";
export const DELETE_FACTOR_FOR = "DELETE_FACTOR_FOR";
export const EXPORT_FACTOR_FOR = "EXPORT_FACTOR_FOR";
export const IMPORT_FACTOR_FOR = "IMPORT_FACTOR_FOR";

export const AGE_GROUP_LIST = "AGE_GROUP_LIST";
export const ADD_AGE_GROUP = "ADD_AGE_GROUP";
export const EDIT_AGE_GROUP = "EDIT_AGE_GROUP";
export const DELETE_AGE_GROUP = "DELETE_AGE_GROUP";
export const EXPORT_AGE_GROUP = "EXPORT_AGE_GROUP";
export const IMPORT_AGE_GROUP = "IMPORT_AGE_GROUP";

export const ACADEMIC_RESULT_GROUP_LIST = "ACADEMIC_RESULT_GROUP_LIST";
export const ADD_ACADEMIC_RESULT_GROUP = "ADD_ACADEMIC_RESULT_GROUP";
export const EDIT_ACADEMIC_RESULT_GROUP = "EDIT_ACADEMIC_RESULT_GROUP";
export const DELETE_ACADEMIC_RESULT_GROUP = "DELETE_ACADEMIC_RESULT_GROUP";
export const EXPORT_ACADEMIC_RESULT_GROUP = "EXPORT_ACADEMIC_RESULT_GROUP";
export const IMPORT_ACADEMIC_RESULT_GROUP = "IMPORT_ACADEMIC_RESULT_GROUP";

export const BACKLOGS_GROUP_LIST = "BACKLOGS_GROUP_LIST";
export const ADD_BACKLOGS_GROUP = "ADD_BACKLOGS_GROUP";
export const EDIT_BACKLOGS_GROUP = "EDIT_BACKLOGS_GROUP";
export const DELETE_BACKLOGS_GROUP = "DELETE_BACKLOGS_GROUP";
export const EXPORT_BACKLOGS_GROUP = "EXPORT_BACKLOGS_GROUP";
export const IMPORT_BACKLOGS_GROUP = "IMPORT_BACKLOGS_GROUP";

export const GAP_GROUP_LIST = "GAP_GROUP_LIST";
export const ADD_GAP_GROUP = "ADD_GAP_GROUP";
export const EDIT_GAP_GROUP = "EDIT_GAP_GROUP";
export const DELETE_GAP_GROUP = "DELETE_GAP_GROUP";
export const EXPORT_GAP_GROUP = "EXPORT_GAP_GROUP";
export const IMPORT_GAP_GROUP = "IMPORT_GAP_GROUP";
