// Institute Type
export const INSTITUTE_TYPE_LIST = "INSTITUTE_TYPE_LIST";
export const ADD_INSTITUTE_TYPE = "ADD_INSTITUTE_TYPE";
export const EDIT_INSTITUTE_TYPE = "EDIT_INSTITUTE_TYPE";
export const DELETE_INSTITUTE_TYPE = "DELETE_INSTITUTE_TYPE";
export const EXPORT_INSTITUTE_TYPE = "EXPORT_INSTITUTE_TYPE";
export const IMPORT_INSTITUTE_TYPE = "IMPORT_INSTITUTE_TYPE";


// Institute Group Name
export const INSTITUTE_GROUP_NAME_LIST = "INSTITUTE_GROUP_NAME_LIST";
export const ADD_INSTITUTE_GROUP_NAME = "ADD_INSTITUTE_GROUP_NAME";
export const EDIT_INSTITUTE_GROUP_NAME = "EDIT_INSTITUTE_GROUP_NAME";
export const DELETE_INSTITUTE_GROUP_NAME = "DELETE_INSTITUTE_GROUP_NAME";
export const EXPORT_INSTITUTE_GROUP_NAME = "EXPORT_INSTITUTE_GROUP_NAME";
export const IMPORT_INSTITUTE_GROUP_NAME = "IMPORT_INSTITUTE_GROUP_NAME";

// Institute Status
export const INSTITUTE_STATUS_LIST = "INSTITUTE_STATUS_LIST";
export const ADD_INSTITUTE_STATUS = "ADD_INSTITUTE_STATUS";
export const EDIT_INSTITUTE_STATUS = "EDIT_INSTITUTE_STATUS";
export const DELETE_INSTITUTE_STATUS = "DELETE_INSTITUTE_STATUS";
export const EXPORT_INSTITUTE_STATUS = "EXPORT_INSTITUTE_STATUS";
export const IMPORT_INSTITUTE_STATUS = "IMPORT_INSTITUTE_STATUS";
// Institute Priority
export const INSTITUTE_PRIORITY_LIST = "INSTITUTE_PRIORITY_LIST";
export const ADD_INSTITUTE_PRIORITY = "ADD_INSTITUTE_PRIORITY";
export const EDIT_INSTITUTE_PRIORITY = "EDIT_INSTITUTE_PRIORITY";
export const DELETE_INSTITUTE_PRIORITY = "DELETE_INSTITUTE_PRIORITY";
export const EXPORT_INSTITUTE_PRIORITY = "EXPORT_INSTITUTE_PRIORITY";
export const IMPORT_INSTITUTE_PRIORITY = "IMPORT_INSTITUTE_PRIORITY";
// Institute Department
export const INSTITUTE_DEPARTMENT_LIST = "INSTITUTE_DEPARTMENT_LIST";
export const ADD_INSTITUTE_DEPARTMENT = "ADD_INSTITUTE_DEPARTMENT";
export const EDIT_INSTITUTE_DEPARTMENT = "EDIT_INSTITUTE_DEPARTMENT";
export const DELETE_INSTITUTE_DEPARTMENT = "DELETE_INSTITUTE_DEPARTMENT";
export const EXPORT_INSTITUTE_DEPARTMENT = "EXPORT_INSTITUTE_DEPARTMENT";
export const IMPORT_INSTITUTE_DEPARTMENT = "IMPORT_INSTITUTE_DEPARTMENT";




