// Institute Type
export const INSTITUTE_TYPE_LIST = "INSTITUTE_TYPE_LIST";
export const ADD_INSTITUTE_TYPE = "ADD_INSTITUTE_TYPE";
export const EDIT_INSTITUTE_TYPE = "EDIT_INSTITUTE_TYPE";
export const DELETE_INSTITUTE_TYPE = "DELETE_INSTITUTE_TYPE";
export const EXPORT_INSTITUTE_TYPE = "EXPORT_INSTITUTE_TYPE";
export const IMPORT_INSTITUTE_TYPE = "IMPORT_INSTITUTE_TYPE";

// Institute Group Name
export const INSTITUTE_GROUP_NAME_LIST = "INSTITUTE_GROUP_NAME_LIST";
export const ADD_INSTITUTE_GROUP_NAME = "ADD_INSTITUTE_GROUP_NAME";
export const EDIT_INSTITUTE_GROUP_NAME = "EDIT_INSTITUTE_GROUP_NAME";
export const DELETE_INSTITUTE_GROUP_NAME = "DELETE_INSTITUTE_GROUP_NAME";
export const EXPORT_INSTITUTE_GROUP_NAME = "EXPORT_INSTITUTE_GROUP_NAME";
export const IMPORT_INSTITUTE_GROUP_NAME = "IMPORT_INSTITUTE_GROUP_NAME";

// Institute Status
export const INSTITUTE_STATUS_LIST = "INSTITUTE_STATUS_LIST";
export const ADD_INSTITUTE_STATUS = "ADD_INSTITUTE_STATUS";
export const EDIT_INSTITUTE_STATUS = "EDIT_INSTITUTE_STATUS";
export const DELETE_INSTITUTE_STATUS = "DELETE_INSTITUTE_STATUS";
export const EXPORT_INSTITUTE_STATUS = "EXPORT_INSTITUTE_STATUS";
export const IMPORT_INSTITUTE_STATUS = "IMPORT_INSTITUTE_STATUS";
// Institute Priority
export const INSTITUTE_PRIORITY_LIST = "INSTITUTE_PRIORITY_LIST";
export const ADD_INSTITUTE_PRIORITY = "ADD_INSTITUTE_PRIORITY";
export const EDIT_INSTITUTE_PRIORITY = "EDIT_INSTITUTE_PRIORITY";
export const DELETE_INSTITUTE_PRIORITY = "DELETE_INSTITUTE_PRIORITY";
export const EXPORT_INSTITUTE_PRIORITY = "EXPORT_INSTITUTE_PRIORITY";
export const IMPORT_INSTITUTE_PRIORITY = "IMPORT_INSTITUTE_PRIORITY";
// Institute Department
export const INSTITUTE_DEPARTMENT_LIST = "INSTITUTE_DEPARTMENT_LIST";
export const ADD_INSTITUTE_DEPARTMENT = "ADD_INSTITUTE_DEPARTMENT";
export const EDIT_INSTITUTE_DEPARTMENT = "EDIT_INSTITUTE_DEPARTMENT";
export const DELETE_INSTITUTE_DEPARTMENT = "DELETE_INSTITUTE_DEPARTMENT";
export const EXPORT_INSTITUTE_DEPARTMENT = "EXPORT_INSTITUTE_DEPARTMENT";
export const IMPORT_INSTITUTE_DEPARTMENT = "IMPORT_INSTITUTE_DEPARTMENT";
// Bank Account For
export const BANK_ACCOUNT_FOR_LIST = "BANK_ACCOUNT_FOR_LIST";
export const ADD_BANK_ACCOUNT_FOR = "ADD_BANK_ACCOUNT_FOR";
export const EDIT_BANK_ACCOUNT_FOR = "EDIT_BANK_ACCOUNT_FOR";
export const DELETE_BANK_ACCOUNT_FOR = "DELETE_BANK_ACCOUNT_FOR";
export const EXPORT_BANK_ACCOUNT_FOR = "EXPORT_BANK_ACCOUNT_FOR";
export const IMPORT_BANK_ACCOUNT_FOR = "IMPORT_BANK_ACCOUNT_FOR";
// When Commission Issue
export const WHEN_COMMISSION_ISSUE_LIST = "WHEN_COMMISSION_ISSUE_LIST";
export const ADD_WHEN_COMMISSION_ISSUE = "ADD_WHEN_COMMISSION_ISSUE";
export const EDIT_WHEN_COMMISSION_ISSUE = "EDIT_WHEN_COMMISSION_ISSUE";
export const DELETE_WHEN_COMMISSION_ISSUE = "DELETE_WHEN_COMMISSION_ISSUE";
export const EXPORT_WHEN_COMMISSION_ISSUE = "EXPORT_WHEN_COMMISSION_ISSUE";
export const IMPORT_WHEN_COMMISSION_ISSUE = "IMPORT_WHEN_COMMISSION_ISSUE";
// Course Level Code
export const COURSE_LEVEL_CODE_LIST = "COURSE_LEVEL_CODE_LIST";
export const ADD_COURSE_LEVEL_CODE = "ADD_COURSE_LEVEL_CODE";
export const EDIT_COURSE_LEVEL_CODE = "EDIT_COURSE_LEVEL_CODE";
export const DELETE_COURSE_LEVEL_CODE = "DELETE_COURSE_LEVEL_CODE";
export const EXPORT_COURSE_LEVEL_CODE = "EXPORT_COURSE_LEVEL_CODE";
export const IMPORT_COURSE_LEVEL_CODE = "IMPORT_COURSE_LEVEL_CODE";
// Course Divided In
export const COURSE_DIVIDED_IN_LIST = "COURSE_DIVIDED_IN_LIST";
export const ADD_COURSE_DIVIDED_IN = "ADD_COURSE_DIVIDED_IN";
export const EDIT_COURSE_DIVIDED_IN = "EDIT_COURSE_DIVIDED_IN";
export const DELETE_COURSE_DIVIDED_IN = "DELETE_COURSE_DIVIDED_IN";
export const EXPORT_COURSE_DIVIDED_IN = "EXPORT_COURSE_DIVIDED_IN";
export const IMPORT_COURSE_DIVIDED_IN = "IMPORT_COURSE_DIVIDED_IN";
// Course Status
export const COURSE_STATUS_LIST = "COURSE_STATUS_LIST";
export const ADD_COURSE_STATUS = "ADD_COURSE_STATUS";
export const EDIT_COURSE_STATUS = "EDIT_COURSE_STATUS";
export const DELETE_COURSE_STATUS = "DELETE_COURSE_STATUS";
export const EXPORT_COURSE_STATUS = "EXPORT_COURSE_STATUS";
export const IMPORT_COURSE_STATUS = "IMPORT_COURSE_STATUS";
// Intake Name
export const INTAKE_NAME_LIST = "INTAKE_NAME_LIST";
export const ADD_INTAKE_NAME = "ADD_INTAKE_NAME";
export const EDIT_INTAKE_NAME = "EDIT_INTAKE_NAME";
export const DELETE_INTAKE_NAME = "DELETE_INTAKE_NAME";
export const EXPORT_INTAKE_NAME = "EXPORT_INTAKE_NAME";
export const IMPORT_INTAKE_NAME = "IMPORT_INTAKE_NAME";
// Course Status for Intake
export const COURSE_STATUS_INTAKE_LIST = "COURSE_STATUS_INTAKE_LIST";
export const ADD_COURSE_STATUS_INTAKE = "ADD_COURSE_STATUS_INTAKE";
export const EDIT_COURSE_STATUS_INTAKE = "EDIT_COURSE_STATUS_INTAKE";
export const DELETE_COURSE_STATUS_INTAKE = "DELETE_COURSE_STATUS_INTAKE";
export const EXPORT_COURSE_STATUS_INTAKE = "EXPORT_COURSE_STATUS_INTAKE";
export const IMPORT_COURSE_STATUS_INTAKE = "IMPORT_COURSE_STATUS_INTAKE";
// Scholarship Based On
export const SCHOLARSHIP_BASED_ON_LIST = "SCHOLARSHIP_BASED_ON_LIST";
export const ADD_SCHOLARSHIP_BASED_ON = "ADD_SCHOLARSHIP_BASED_ON";
export const EDIT_SCHOLARSHIP_BASED_ON = "EDIT_SCHOLARSHIP_BASED_ON";
export const DELETE_SCHOLARSHIP_BASED_ON = "DELETE_SCHOLARSHIP_BASED_ON";
export const EXPORT_SCHOLARSHIP_BASED_ON = "EXPORT_SCHOLARSHIP_BASED_ON";
export const IMPORT_SCHOLARSHIP_BASED_ON = "IMPORT_SCHOLARSHIP_BASED_ON";
// Course Level
export const COURSE_LEVEL_LIST = "COURSE_LEVEL_LIST";
export const ADD_COURSE_LEVEL = "ADD_COURSE_LEVEL";
export const EDIT_COURSE_LEVEL = "EDIT_COURSE_LEVEL";
export const DELETE_COURSE_LEVEL = "DELETE_COURSE_LEVEL";
export const EXPORT_COURSE_LEVEL = "EXPORT_COURSE_LEVEL";
export const IMPORT_COURSE_LEVEL = "IMPORT_COURSE_LEVEL";
// Course Duration
export const COURSE_DURATION_LIST = "COURSE_DURATION_LIST";
export const ADD_COURSE_DURATION = "ADD_COURSE_DURATION";
export const EDIT_COURSE_DURATION = "EDIT_COURSE_DURATION";
export const DELETE_COURSE_DURATION = "DELETE_COURSE_DURATION";
export const EXPORT_COURSE_DURATION = "EXPORT_COURSE_DURATION";
export const IMPORT_COURSE_DURATION = "IMPORT_COURSE_DURATION";














