// Document Category
export const DOCUMENT_CATEGORY_LIST = "DOCUMENT_CATEGORY_LIST";
export const ADD_DOCUMENT_CATEGORY = "ADD_DOCUMENT_CATEGORY";
export const EDIT_DOCUMENT_CATEGORY = "EDIT_DOCUMENT_CATEGORY";
export const DELETE_DOCUMENT_CATEGORY = "DELETE_DOCUMENT_CATEGORY";
export const EXPORT_DOCUMENT_CATEGORY = "EXPORT_DOCUMENT_CATEGORY";
export const IMPORT_DOCUMENT_CATEGORY = "IMPORT_DOCUMENT_CATEGORY";
// Document Name
export const DOCUMENT_NAME_LIST = "DOCUMENT_NAME_LIST";
export const ADD_DOCUMENT_NAME = "ADD_DOCUMENT_NAME";
export const EDIT_DOCUMENT_NAME = "EDIT_DOCUMENT_NAME";
export const DELETE_DOCUMENT_NAME = "DELETE_DOCUMENT_NAME";
export const EXPORT_DOCUMENT_NAME = "EXPORT_DOCUMENT_NAME";
export const IMPORT_DOCUMENT_NAME = "IMPORT_DOCUMENT_NAME";
// Document Type
export const DOCUMENT_TYPE_LIST = "DOCUMENT_TYPE_LIST";
export const ADD_DOCUMENT_TYPE = "ADD_DOCUMENT_TYPE";
export const EDIT_DOCUMENT_TYPE = "EDIT_DOCUMENT_TYPE";
export const DELETE_DOCUMENT_TYPE = "DELETE_DOCUMENT_TYPE";
export const EXPORT_DOCUMENT_TYPE = "EXPORT_DOCUMENT_TYPE";
export const IMPORT_DOCUMENT_TYPE = "IMPORT_DOCUMENT_TYPE";
// Purpose of Visit
export const PURPOSE_OF_VISIT_LIST = "PURPOSE_OF_VISIT_LIST";
export const ADD_PURPOSE_OF_VISIT = "ADD_PURPOSE_OF_VISIT";
export const EDIT_PURPOSE_OF_VISIT = "EDIT_PURPOSE_OF_VISIT";
export const DELETE_PURPOSE_OF_VISIT = "DELETE_PURPOSE_OF_VISIT";
export const EXPORT_PURPOSE_OF_VISIT = "EXPORT_PURPOSE_OF_VISIT";
export const IMPORT_PURPOSE_OF_VISIT = "IMPORT_PURPOSE_OF_VISIT";
// Documents For
export const DOCUMENTS_FOR_LIST = "DOCUMENTS_FOR_LIST";
export const ADD_DOCUMENTS_FOR = "ADD_DOCUMENTS_FOR";
export const EDIT_DOCUMENTS_FOR = "EDIT_DOCUMENTS_FOR";
export const DELETE_DOCUMENTS_FOR = "DELETE_DOCUMENTS_FOR";
export const EXPORT_DOCUMENTS_FOR = "EXPORT_DOCUMENTS_FOR";
export const IMPORT_DOCUMENTS_FOR = "IMPORT_DOCUMENTS_FOR";
// Required Documents (General)
export const REQUIRED_DOCUMENT_GENERAL_LIST = "REQUIRED_DOCUMENT_GENERAL_LIST";
export const ADD_REQUIRED_DOCUMENT_GENERAL = "ADD_REQUIRED_DOCUMENT_GENERAL";
export const EDIT_REQUIRED_DOCUMENT_GENERAL = "EDIT_REQUIRED_DOCUMENT_GENERAL";
export const DELETE_REQUIRED_DOCUMENT_GENERAL = "DELETE_REQUIRED_DOCUMENT_GENERAL";
export const EXPORT_REQUIRED_DOCUMENT_GENERAL = "EXPORT_REQUIRED_DOCUMENT_GENERAL";
export const IMPORT_REQUIRED_DOCUMENT_GENERAL = "IMPORT_REQUIRED_DOCUMENT_GENERAL";
// Process Status Name
export const PROCESS_STATUS_NAME_LIST = "PROCESS_STATUS_NAME_LIST";
export const ADD_PROCESS_STATUS_NAME = "ADD_PROCESS_STATUS_NAME";
export const EDIT_PROCESS_STATUS_NAME = "EDIT_PROCESS_STATUS_NAME";
export const DELETE_PROCESS_STATUS_NAME = "DELETE_PROCESS_STATUS_NAME";
export const EXPORT_PROCESS_STATUS_NAME = "EXPORT_PROCESS_STATUS_NAME";
export const IMPORT_PROCESS_STATUS_NAME = "IMPORT_PROCESS_STATUS_NAME";

// Process Sub-Status Name
export const PROCESS_SUB_STATUS_NAME_LIST = "PROCESS_SUB_STATUS_NAME_LIST";
export const ADD_PROCESS_SUB_STATUS_NAME = "ADD_PROCESS_SUB_STATUS_NAME";
export const EDIT_PROCESS_SUB_STATUS_NAME = "EDIT_PROCESS_SUB_STATUS_NAME";
export const DELETE_PROCESS_SUB_STATUS_NAME = "DELETE_PROCESS_SUB_STATUS_NAME";
export const EXPORT_PROCESS_SUB_STATUS_NAME = "EXPORT_PROCESS_SUB_STATUS_NAME";
export const IMPORT_PROCESS_SUB_STATUS_NAME = "IMPORT_PROCESS_SUB_STATUS_NAME";
// Process Type
export const PROCESS_TYPE_LIST = "PROCESS_TYPE_LIST";
export const ADD_PROCESS_TYPE = "ADD_PROCESS_TYPE";
export const EDIT_PROCESS_TYPE = "EDIT_PROCESS_TYPE";
export const DELETE_PROCESS_TYPE = "DELETE_PROCESS_TYPE";
export const EXPORT_PROCESS_TYPE = "EXPORT_PROCESS_TYPE";
export const IMPORT_PROCESS_TYPE = "IMPORT_PROCESS_TYPE";
// Payment To
export const PAYMENT_TO_LIST = "PAYMENT_TO_LIST";
export const ADD_PAYMENT_TO = "ADD_PAYMENT_TO";
export const EDIT_PAYMENT_TO = "EDIT_PAYMENT_TO";
export const DELETE_PAYMENT_TO = "DELETE_PAYMENT_TO";
export const EXPORT_PAYMENT_TO = "EXPORT_PAYMENT_TO";
export const IMPORT_PAYMENT_TO = "IMPORT_PAYMENT_TO";
// Payment Category
export const PAYMENT_CATEGORY_LIST = "PAYMENT_CATEGORY_LIST";
export const ADD_PAYMENT_CATEGORY = "ADD_PAYMENT_CATEGORY";
export const EDIT_PAYMENT_CATEGORY = "EDIT_PAYMENT_CATEGORY";
export const DELETE_PAYMENT_CATEGORY = "DELETE_PAYMENT_CATEGORY";
export const EXPORT_PAYMENT_CATEGORY = "EXPORT_PAYMENT_CATEGORY";
export const IMPORT_PAYMENT_CATEGORY = "IMPORT_PAYMENT_CATEGORY";










