
// GENDER
export const GENDER_LIST = "GENDER_LIST";
export const ADD_GENDER = "ADD_GENDER";
export const EDIT_GENDER = "EDIT_GENDER";
export const DELETE_GENDER = "DELETE_GENDER";
export const EXPORT_GENDER = "EXPORT_GENDER";
export const IMPORT_GENDER = "IMPORT_GENDER";

// MARITAL_STATUS
export const MARITAL_STATUS_LIST = "MARITAL_STATUS_LIST";
export const ADD_MARITAL_STATUS = "ADD_MARITAL_STATUS";
export const EDIT_MARITAL_STATUS = "EDIT_MARITAL_STATUS";
export const DELETE_MARITAL_STATUS = "DELETE_MARITAL_STATUS";
export const EXPORT_MARITAL_STATUS = "EXPORT_MARITAL_STATUS";
export const IMPORT_MARITAL_STATUS = "IMPORT_MARITAL_STATUS";

// CONTINENT
export const CONTINENT_LIST = "CONTINENT_LIST";
export const ADD_CONTINENT = "ADD_CONTINENT";
export const EDIT_CONTINENT = "EDIT_CONTINENT";
export const DELETE_CONTINENT = "DELETE_CONTINENT";
export const EXPORT_CONTINENT = "EXPORT_CONTINENT";
export const IMPORT_CONTINENT = "IMPORT_CONTINENT";

// CIVIL_ID_NAME
export const CIVIL_ID_NAME_LIST = "CIVIL_ID_NAME_LIST";
export const ADD_CIVIL_ID_NAME = "ADD_CIVIL_ID_NAME";
export const EDIT_CIVIL_ID_NAME = "EDIT_CIVIL_ID_NAME";
export const DELETE_CIVIL_ID_NAME = "DELETE_CIVIL_ID_NAME";
export const EXPORT_CIVIL_ID_NAME = "EXPORT_CIVIL_ID_NAME";
export const IMPORT_CIVIL_ID_NAME = "IMPORT_CIVIL_ID_NAME";

// RELATION
export const RELATION_LIST = "RELATION_LIST";
export const ADD_RELATION = "ADD_RELATION";
export const EDIT_RELATION = "EDIT_RELATION";
export const DELETE_RELATION = "DELETE_RELATION";
export const EXPORT_RELATION = "EXPORT_RELATION";
export const IMPORT_RELATION = "IMPORT_RELATION";