
// GENDER
export const GENDER_LIST = "GENDER_LIST";
export const ADD_GENDER = "ADD_GENDER";
export const EDIT_GENDER = "EDIT_GENDER";
export const DELETE_GENDER = "DELETE_GENDER";
export const EXPORT_GENDER = "EXPORT_GENDER";
export const IMPORT_GENDER = "IMPORT_GENDER";

// MARITAL_STATUS
export const MARITAL_STATUS_LIST = "MARITAL_STATUS_LIST";
export const ADD_MARITAL_STATUS = "ADD_MARITAL_STATUS";
export const EDIT_MARITAL_STATUS = "EDIT_MARITAL_STATUS";
export const DELETE_MARITAL_STATUS = "DELETE_MARITAL_STATUS";
export const EXPORT_MARITAL_STATUS = "EXPORT_MARITAL_STATUS";
export const IMPORT_MARITAL_STATUS = "IMPORT_MARITAL_STATUS";

// CONTINENT
export const CONTINENT_LIST = "CONTINENT_LIST";
export const ADD_CONTINENT = "ADD_CONTINENT";
export const EDIT_CONTINENT = "EDIT_CONTINENT";
export const DELETE_CONTINENT = "DELETE_CONTINENT";
export const EXPORT_CONTINENT = "EXPORT_CONTINENT";
export const IMPORT_CONTINENT = "IMPORT_CONTINENT";

// CIVIL_ID_NAME
export const CIVIL_ID_NAME_LIST = "CIVIL_ID_NAME_LIST";
export const ADD_CIVIL_ID_NAME = "ADD_CIVIL_ID_NAME";
export const EDIT_CIVIL_ID_NAME = "EDIT_CIVIL_ID_NAME";
export const DELETE_CIVIL_ID_NAME = "DELETE_CIVIL_ID_NAME";
export const EXPORT_CIVIL_ID_NAME = "EXPORT_CIVIL_ID_NAME";
export const IMPORT_CIVIL_ID_NAME = "IMPORT_CIVIL_ID_NAME";

// RELATION
export const RELATION_LIST = "RELATION_LIST";
export const ADD_RELATION = "ADD_RELATION";
export const EDIT_RELATION = "EDIT_RELATION";
export const DELETE_RELATION = "DELETE_RELATION";
export const EXPORT_RELATION = "EXPORT_RELATION";
export const IMPORT_RELATION = "IMPORT_RELATION";

// TIME_ZONE
export const TIME_ZONE_LIST = "TIME_ZONE_LIST";
export const ADD_TIME_ZONE = "ADD_TIME_ZONE";
export const EDIT_TIME_ZONE = "EDIT_TIME_ZONE";
export const DELETE_TIME_ZONE = "DELETE_TIME_ZONE";
export const EXPORT_TIME_ZONE = "EXPORT_TIME_ZONE";
export const IMPORT_TIME_ZONE = "IMPORT_TIME_ZONE";

// COUNTRY
export const COUNTRY_LIST = "COUNTRY_LIST";
export const ADD_COUNTRY = "ADD_COUNTRY";
export const EDIT_COUNTRY = "EDIT_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const EXPORT_COUNTRY = "EXPORT_COUNTRY";
export const IMPORT_COUNTRY = "IMPORT_COUNTRY";
// STATE
export const STATE_LIST = "STATE_LIST";
export const ADD_STATE = "ADD_STATE";
export const EDIT_STATE = "EDIT_STATE";
export const DELETE_STATE = "DELETE_STATE";
export const EXPORT_STATE = "EXPORT_STATE";
export const IMPORT_STATE = "IMPORT_STATE";
export const STATE_LIST_BY_COUNTRY = "STATE_LIST_BY_COUNTRY";

// DISTRICT
export const DISTRICT_LIST = "DISTRICT_LIST";
export const ADD_DISTRICT = "ADD_DISTRICT";
export const EDIT_DISTRICT = "EDIT_DISTRICT";
export const DELETE_DISTRICT = "DELETE_DISTRICT";
export const EXPORT_DISTRICT = "EXPORT_DISTRICT";
export const IMPORT_DISTRICT = "IMPORT_DISTRICT";
export const DISTRICT_LIST_BY_STATE = "DISTRICT_LIST_BY_STATE";


// CITY
export const CITY_LIST = "CITY_LIST";
export const ADD_CITY = "ADD_CITY";
export const EDIT_CITY = "EDIT_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const EXPORT_CITY = "EXPORT_CITY";
export const IMPORT_CITY = "IMPORT_CITY";