
// GENDER
export const GENDER_LIST = "GENDER_LIST";
export const ADD_GENDER = "ADD_GENDER";
export const EDIT_GENDER = "EDIT_GENDER";
export const DELETE_GENDER = "DELETE_GENDER";
export const EXPORT_GENDER = "EXPORT_GENDER";
export const IMPORT_GENDER = "IMPORT_GENDER";

// MARITAL_STATUS
export const MARITAL_STATUS_LIST = "MARITAL_STATUS_LIST";
export const ADD_MARITAL_STATUS = "ADD_MARITAL_STATUS";
export const EDIT_MARITAL_STATUS = "EDIT_MARITAL_STATUS";
export const DELETE_MARITAL_STATUS = "DELETE_MARITAL_STATUS";
export const EXPORT_MARITAL_STATUS = "EXPORT_MARITAL_STATUS";
export const IMPORT_MARITAL_STATUS = "IMPORT_MARITAL_STATUS";