// Representing Country
export const REPRESENTING_COUNTRY_LIST = "REPRESENTING_COUNTRY_LIST";
export const ADD_REPRESENTING_COUNTRY = "ADD_REPRESENTING_COUNTRY";
export const EDIT_REPRESENTING_COUNTRY = "EDIT_REPRESENTING_COUNTRY";
export const DELETE_REPRESENTING_COUNTRY = "DELETE_REPRESENTING_COUNTRY";
export const EXPORT_REPRESENTING_COUNTRY = "EXPORT_REPRESENTING_COUNTRY";
export const IMPORT_REPRESENTING_COUNTRY = "IMPORT_REPRESENTING_COUNTRY";
// Visa Major Category
export const VISA_MAJOR_CATEGORY_LIST = "VISA_MAJOR_CATEGORY_LIST";
export const ADD_VISA_MAJOR_CATEGORY = "ADD_VISA_MAJOR_CATEGORY";
export const EDIT_VISA_MAJOR_CATEGORY = "EDIT_VISA_MAJOR_CATEGORY";
export const DELETE_VISA_MAJOR_CATEGORY = "DELETE_VISA_MAJOR_CATEGORY";
export const EXPORT_VISA_MAJOR_CATEGORY = "EXPORT_VISA_MAJOR_CATEGORY";
export const IMPORT_VISA_MAJOR_CATEGORY = "IMPORT_VISA_MAJOR_CATEGORY";
// Applicant Type
export const APPLICANT_TYPE_LIST = "APPLICANT_TYPE_LIST";
export const ADD_APPLICANT_TYPE = "ADD_APPLICANT_TYPE";
export const EDIT_APPLICANT_TYPE = "EDIT_APPLICANT_TYPE";
export const DELETE_APPLICANT_TYPE = "DELETE_APPLICANT_TYPE";
export const EXPORT_APPLICANT_TYPE = "EXPORT_APPLICANT_TYPE";
export const IMPORT_APPLICANT_TYPE = "IMPORT_APPLICANT_TYPE";
// VISA ELIGIBILITY TYPE
export const VISA_ELIGIBILITY_TYPE_LIST = "VISA_ELIGIBILITY_TYPE_LIST";
export const ADD_VISA_ELIGIBILITY_TYPE = "ADD_VISA_ELIGIBILITY_TYPE";
export const EDIT_VISA_ELIGIBILITY_TYPE = "EDIT_VISA_ELIGIBILITY_TYPE";
export const DELETE_VISA_ELIGIBILITY_TYPE = "DELETE_VISA_ELIGIBILITY_TYPE";
export const EXPORT_VISA_ELIGIBILITY_TYPE = "EXPORT_VISA_ELIGIBILITY_TYPE";
export const IMPORT_VISA_ELIGIBILITY_TYPE = "IMPORT_VISA_ELIGIBILITY_TYPE";
// VISA STATUS
export const VISA_STATUS_LIST = "VISA_STATUS_LIST";
export const ADD_VISA_STATUS = "ADD_VISA_STATUS";
export const EDIT_VISA_STATUS = "EDIT_VISA_STATUS";
export const DELETE_VISA_STATUS = "DELETE_VISA_STATUS";
export const EXPORT_VISA_STATUS = "EXPORT_VISA_STATUS";
export const IMPORT_VISA_STATUS = "IMPORT_VISA_STATUS";
// POSSIBILITY LEVEL
export const POSSIBILITY_LEVEL_LIST = "POSSIBILITY_LEVEL_LIST";
export const ADD_POSSIBILITY_LEVEL = "ADD_POSSIBILITY_LEVEL";
export const EDIT_POSSIBILITY_LEVEL = "EDIT_POSSIBILITY_LEVEL";
export const DELETE_POSSIBILITY_LEVEL = "DELETE_POSSIBILITY_LEVEL";
export const EXPORT_POSSIBILITY_LEVEL = "EXPORT_POSSIBILITY_LEVEL";
export const IMPORT_POSSIBILITY_LEVEL = "IMPORT_POSSIBILITY_LEVEL";

// ---------------- VISA NAME ----------------
export const VISA_NAME_LIST = "VISA_NAME_LIST";
export const ADD_VISA_NAME = "ADD_VISA_NAME";
export const EDIT_VISA_NAME = "EDIT_VISA_NAME";
export const DELETE_VISA_NAME = "DELETE_VISA_NAME";
export const EXPORT_VISA_NAME = "EXPORT_VISA_NAME";
export const IMPORT_VISA_NAME = "IMPORT_VISA_NAME";




