# Generated by Django 4.2.27 on 2025-12-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module3d',
            name='color',
        ),
        migrations.AddField(
            model_name='module3d',
            name='colors',
            field=models.JSONField(default=dict),
        ),
    ]
