# Generated by Django 4.2.27 on 2025-12-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_module3d_color_module3d_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module3d',
            old_name='colors',
            new_name='color',
        ),
    ]
