// Work Rights
export const WORK_RIGHTS_LIST = "WORK_RIGHTS_LIST";
export const ADD_WORK_RIGHTS = "ADD_WORK_RIGHTS";
export const EDIT_WORK_RIGHTS = "EDIT_WORK_RIGHTS";
export const DELETE_WORK_RIGHTS = "DELETE_WORK_RIGHTS";
export const EXPORT_WORK_RIGHTS = "EXPORT_WORK_RIGHTS";
export const IMPORT_WORK_RIGHTS = "IMPORT_WORK_RIGHTS";
// Work Rights During Study
export const WORK_RIGHTS_DURING_STUDY_LIST = "WORK_RIGHTS_DURING_STUDY_LIST";
export const ADD_WORK_RIGHTS_DURING_STUDY = "ADD_WORK_RIGHTS_DURING_STUDY";
export const EDIT_WORK_RIGHTS_DURING_STUDY = "EDIT_WORK_RIGHTS_DURING_STUDY";
export const DELETE_WORK_RIGHTS_DURING_STUDY = "DELETE_WORK_RIGHTS_DURING_STUDY";
export const EXPORT_WORK_RIGHTS_DURING_STUDY = "EXPORT_WORK_RIGHTS_DURING_STUDY";
export const IMPORT_WORK_RIGHTS_DURING_STUDY = "IMPORT_WORK_RIGHTS_DURING_STUDY";
// Work Rights During Vacation
export const WORK_RIGHTS_DURING_VACATION_LIST = "WORK_RIGHTS_DURING_VACATION_LIST";
export const ADD_WORK_RIGHTS_DURING_VACATION = "ADD_WORK_RIGHTS_DURING_VACATION";
export const EDIT_WORK_RIGHTS_DURING_VACATION = "EDIT_WORK_RIGHTS_DURING_VACATION";
export const DELETE_WORK_RIGHTS_DURING_VACATION = "DELETE_WORK_RIGHTS_DURING_VACATION";
export const EXPORT_WORK_RIGHTS_DURING_VACATION = "EXPORT_WORK_RIGHTS_DURING_VACATION";
export const IMPORT_WORK_RIGHTS_DURING_VACATION = "IMPORT_WORK_RIGHTS_DURING_VACATION";
// Work Right After Study
export const WORK_RIGHTS_AFTER_STUDY_LIST = "WORK_RIGHTS_AFTER_STUDY_LIST";
export const ADD_WORK_RIGHTS_AFTER_STUDY = "ADD_WORK_RIGHTS_AFTER_STUDY";
export const EDIT_WORK_RIGHTS_AFTER_STUDY = "EDIT_WORK_RIGHTS_AFTER_STUDY";
export const DELETE_WORK_RIGHTS_AFTER_STUDY = "DELETE_WORK_RIGHTS_AFTER_STUDY";
export const EXPORT_WORK_RIGHTS_AFTER_STUDY = "EXPORT_WORK_RIGHTS_AFTER_STUDY";
export const IMPORT_WORK_RIGHTS_AFTER_STUDY = "IMPORT_WORK_RIGHTS_AFTER_STUDY";
// PR Possibility
export const PR_POSSIBILITY_LIST = "PR_POSSIBILITY_LIST";
export const ADD_PR_POSSIBILITY = "ADD_PR_POSSIBILITY";
export const EDIT_PR_POSSIBILITY = "EDIT_PR_POSSIBILITY";
export const DELETE_PR_POSSIBILITY = "DELETE_PR_POSSIBILITY";
export const EXPORT_PR_POSSIBILITY = "EXPORT_PR_POSSIBILITY";
export const IMPORT_PR_POSSIBILITY = "IMPORT_PR_POSSIBILITY";
// Spouse Can Apply with Candidate?
export const SPOUSE_APPLY_WITH_CANDIDATE_LIST = "SPOUSE_APPLY_WITH_CANDIDATE_LIST";
export const ADD_SPOUSE_APPLY_WITH_CANDIDATE = "ADD_SPOUSE_APPLY_WITH_CANDIDATE";
export const EDIT_SPOUSE_APPLY_WITH_CANDIDATE = "EDIT_SPOUSE_APPLY_WITH_CANDIDATE";
export const DELETE_SPOUSE_APPLY_WITH_CANDIDATE = "DELETE_SPOUSE_APPLY_WITH_CANDIDATE";
export const EXPORT_SPOUSE_APPLY_WITH_CANDIDATE = "EXPORT_SPOUSE_APPLY_WITH_CANDIDATE";
export const IMPORT_SPOUSE_APPLY_WITH_CANDIDATE = "IMPORT_SPOUSE_APPLY_WITH_CANDIDATE";
// --- Spouse Visa Category ---
export const SPOUSE_VISA_CATEGORY_LIST = "SPOUSE_VISA_CATEGORY_LIST";
export const ADD_SPOUSE_VISA_CATEGORY = "ADD_SPOUSE_VISA_CATEGORY";
export const EDIT_SPOUSE_VISA_CATEGORY = "EDIT_SPOUSE_VISA_CATEGORY";
export const DELETE_SPOUSE_VISA_CATEGORY = "DELETE_SPOUSE_VISA_CATEGORY";
export const EXPORT_SPOUSE_VISA_CATEGORY = "EXPORT_SPOUSE_VISA_CATEGORY";
export const IMPORT_SPOUSE_VISA_CATEGORY = "IMPORT_SPOUSE_VISA_CATEGORY";
// Spouse Work Rights
export const SPOUSE_WORK_RIGHTS_LIST = "SPOUSE_WORK_RIGHTS_LIST";
export const ADD_SPOUSE_WORK_RIGHTS = "ADD_SPOUSE_WORK_RIGHTS";
export const EDIT_SPOUSE_WORK_RIGHTS = "EDIT_SPOUSE_WORK_RIGHTS";
export const DELETE_SPOUSE_WORK_RIGHTS = "DELETE_SPOUSE_WORK_RIGHTS";
export const EXPORT_SPOUSE_WORK_RIGHTS = "EXPORT_SPOUSE_WORK_RIGHTS";
export const IMPORT_SPOUSE_WORK_RIGHTS = "IMPORT_SPOUSE_WORK_RIGHTS";
// Children Can Apply with Candidate
export const CHILDREN_APPLY_WITH_CANDIDATE_LIST = "CHILDREN_APPLY_WITH_CANDIDATE_LIST";
export const ADD_CHILDREN_APPLY_WITH_CANDIDATE = "ADD_CHILDREN_APPLY_WITH_CANDIDATE";
export const EDIT_CHILDREN_APPLY_WITH_CANDIDATE = "EDIT_CHILDREN_APPLY_WITH_CANDIDATE";
export const DELETE_CHILDREN_APPLY_WITH_CANDIDATE = "DELETE_CHILDREN_APPLY_WITH_CANDIDATE";
export const EXPORT_CHILDREN_APPLY_WITH_CANDIDATE = "EXPORT_CHILDREN_APPLY_WITH_CANDIDATE";
export const IMPORT_CHILDREN_APPLY_WITH_CANDIDATE = "IMPORT_CHILDREN_APPLY_WITH_CANDIDATE";
// Children Visa Category
export const CHILDREN_VISA_CATEGORY_LIST = "CHILDREN_VISA_CATEGORY_LIST";
export const ADD_CHILDREN_VISA_CATEGORY = "ADD_CHILDREN_VISA_CATEGORY";
export const EDIT_CHILDREN_VISA_CATEGORY = "EDIT_CHILDREN_VISA_CATEGORY";
export const DELETE_CHILDREN_VISA_CATEGORY = "DELETE_CHILDREN_VISA_CATEGORY";
export const EXPORT_CHILDREN_VISA_CATEGORY = "EXPORT_CHILDREN_VISA_CATEGORY";
export const IMPORT_CHILDREN_VISA_CATEGORY = "IMPORT_CHILDREN_VISA_CATEGORY";

// Children Study / Work Rights
export const CHILDREN_STUDY_WORK_RIGHTS_LIST = "CHILDREN_STUDY_WORK_RIGHTS_LIST";
export const ADD_CHILDREN_STUDY_WORK_RIGHTS = "ADD_CHILDREN_STUDY_WORK_RIGHTS";
export const EDIT_CHILDREN_STUDY_WORK_RIGHTS = "EDIT_CHILDREN_STUDY_WORK_RIGHTS";
export const DELETE_CHILDREN_STUDY_WORK_RIGHTS = "DELETE_CHILDREN_STUDY_WORK_RIGHTS";
export const EXPORT_CHILDREN_STUDY_WORK_RIGHTS = "EXPORT_CHILDREN_STUDY_WORK_RIGHTS";
export const IMPORT_CHILDREN_STUDY_WORK_RIGHTS = "IMPORT_CHILDREN_STUDY_WORK_RIGHTS";

// VISA MAIN CATEGORY 

export const VISA_MAIN_CATEGORY_LIST = "VISA_MAIN_CATEGORY_LIST";
export const ADD_VISA_MAIN_CATEGORY = "ADD_VISA_MAIN_CATEGORY";
export const EDIT_VISA_MAIN_CATEGORY = "EDIT_VISA_MAIN_CATEGORY";
export const DELETE_VISA_MAIN_CATEGORY = "DELETE_VISA_MAIN_CATEGORY";
export const EXPORT_VISA_MAIN_CATEGORY = "EXPORT_VISA_MAIN_CATEGORY";
export const IMPORT_VISA_MAIN_CATEGORY = "IMPORT_VISA_MAIN_CATEGORY";









