export const LOGIN_USER = "LOGIN_USER"
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
// export const TWO_STEP_VERIFICATION = "TWO_STEP_VERIFICATION"

// export const LOGOUT_USER = "LOGOUT_USER"
// export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
// export const API_ERROR = "LOGIN_API_ERROR"
// export const FORGET_PASSWORD = "FORGET_PASSWORD"
// export const RESET_PASSWORD = "RESET_PASSWORD"

