// Job Type
export const JOB_TYPE_LIST = "JOB_TYPE_LIST";
export const ADD_JOB_TYPE = "ADD_JOB_TYPE";
export const EDIT_JOB_TYPE = "EDIT_JOB_TYPE";
export const DELETE_JOB_TYPE = "DELETE_JOB_TYPE";
export const EXPORT_JOB_TYPE = "EXPORT_JOB_TYPE";
export const IMPORT_JOB_TYPE = "IMPORT_JOB_TYPE";

// Mode of Salary
export const MODE_OF_SALARY_LIST = "MODE_OF_SALARY_LIST";
export const ADD_MODE_OF_SALARY = "ADD_MODE_OF_SALARY";
export const EDIT_MODE_OF_SALARY = "EDIT_MODE_OF_SALARY";
export const DELETE_MODE_OF_SALARY = "DELETE_MODE_OF_SALARY";
export const EXPORT_MODE_OF_SALARY = "EXPORT_MODE_OF_SALARY";
export const IMPORT_MODE_OF_SALARY = "IMPORT_MODE_OF_SALARY";

// IT Return Status
export const IT_RETURN_STATUS_LIST = "IT_RETURN_STATUS_LIST";
export const ADD_IT_RETURN_STATUS = "ADD_IT_RETURN_STATUS";
export const EDIT_IT_RETURN_STATUS = "EDIT_IT_RETURN_STATUS";
export const DELETE_IT_RETURN_STATUS = "DELETE_IT_RETURN_STATUS";
export const EXPORT_IT_RETURN_STATUS = "EXPORT_IT_RETURN_STATUS";
export const IMPORT_IT_RETURN_STATUS = "IMPORT_IT_RETURN_STATUS";

// Occupation Type
export const OCCUPATION_TYPE_LIST = "OCCUPATION_TYPE_LIST";
export const ADD_OCCUPATION_TYPE = "ADD_OCCUPATION_TYPE";
export const EDIT_OCCUPATION_TYPE = "EDIT_OCCUPATION_TYPE";
export const DELETE_OCCUPATION_TYPE = "DELETE_OCCUPATION_TYPE";
export const EXPORT_OCCUPATION_TYPE = "EXPORT_OCCUPATION_TYPE";
export const IMPORT_OCCUPATION_TYPE = "IMPORT_OCCUPATION_TYPE";

// Occupation Prospect
export const OCCUPATION_PROSPECT_LIST = "OCCUPATION_PROSPECT_LIST";
export const ADD_OCCUPATION_PROSPECT = "ADD_OCCUPATION_PROSPECT";
export const EDIT_OCCUPATION_PROSPECT = "EDIT_OCCUPATION_PROSPECT";
export const DELETE_OCCUPATION_PROSPECT = "DELETE_OCCUPATION_PROSPECT";
export const EXPORT_OCCUPATION_PROSPECT = "EXPORT_OCCUPATION_PROSPECT";
export const IMPORT_OCCUPATION_PROSPECT = "IMPORT_OCCUPATION_PROSPECT";




