export const DEPARTMENT_LIST = "DEPARTMENT_LIST";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const EXPORT_DEPARTMENT = "EXPORT_DEPARTMENT";
export const IMPORT_DEPARTMENT = "IMPORT_DEPARTMENT";

export const EMPLOYEE_TYPE_LIST = "EMPLOYEE_TYPE_LIST";
export const ADD_EMPLOYEE_TYPE = "ADD_EMPLOYEE_TYPE";
export const EDIT_EMPLOYEE_TYPE = "EDIT_EMPLOYEE_TYPE";
export const DELETE_EMPLOYEE_TYPE = "DELETE_EMPLOYEE_TYPE";
export const EXPORT_EMPLOYEE_TYPE = "EXPORT_EMPLOYEE_TYPE";
export const IMPORT_EMPLOYEE_TYPE = "IMPORT_EMPLOYEE_TYPE";

export const COMPANY_LIST = "COMPANY_LIST";
export const ADD_COMPANY = "ADD_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const EXPORT_COMPANY = "EXPORT_COMPANY";
export const IMPORT_COMPANY = "IMPORT_COMPANY";