export const DEPARTMENT_LIST = "DEPARTMENT_LIST";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const EXPORT_DEPARTMENT = "EXPORT_DEPARTMENT";
export const IMPORT_DEPARTMENT = "IMPORT_DEPARTMENT";

// employee type
export const EMPLOYEE_TYPE_LIST = "EMPLOYEE_TYPE_LIST";
export const ADD_EMPLOYEE_TYPE = "ADD_EMPLOYEE_TYPE";
export const EDIT_EMPLOYEE_TYPE = "EDIT_EMPLOYEE_TYPE";
export const DELETE_EMPLOYEE_TYPE = "DELETE_EMPLOYEE_TYPE";
export const EXPORT_EMPLOYEE_TYPE = "EXPORT_EMPLOYEE_TYPE";
export const IMPORT_EMPLOYEE_TYPE = "IMPORT_EMPLOYEE_TYPE";

// company type
export const COMPANY_LIST = "COMPANY_LIST";
export const ADD_COMPANY = "ADD_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const EXPORT_COMPANY = "EXPORT_COMPANY";
export const IMPORT_COMPANY = "IMPORT_COMPANY";

// stakeholder categories
export const STAKEHOLDER_CATEGORY_LIST = "STAKEHOLDER_CATEGORY_LIST";
export const ADD_STAKEHOLDER_CATEGORY = "ADD_STAKEHOLDER_CATEGORY";
export const EDIT_STAKEHOLDER_CATEGORY = "EDIT_STAKEHOLDER_CATEGORY";
export const DELETE_STAKEHOLDER_CATEGORY = "DELETE_STAKEHOLDER_CATEGORY";
export const EXPORT_STAKEHOLDER_CATEGORY = "EXPORT_STAKEHOLDER_CATEGORY";
export const IMPORT_STAKEHOLDER_CATEGORY = "IMPORT_STAKEHOLDER_CATEGORY";