export const DEPARTMENT_LIST = "DEPARTMENT_LIST";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const EXPORT_DEPARTMENT = "EXPORT_DEPARTMENT";
export const IMPORT_DEPARTMENT = "IMPORT_DEPARTMENT";

export const COUNTRY_LIST   = "COUNTRY_LIST";
export const ADD_COUNTRY    = "ADD_COUNTRY";
export const EDIT_COUNTRY   = "EDIT_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const EXPORT_COUNTRY = "EXPORT_COUNTRY";
export const IMPORT_COUNTRY = "IMPORT_COUNTRY";

export const STATE_LIST     =   "STATE_LIST";
export const ADD_STATE      = "ADD_STATE";
export const EDIT_STATE     = "EDIT_STATE";
export const DELETE_STATE   = "DELETE_STATE";
export const EXPORT_STATE   = "EXPORT_STATE";
export const IMPORT_STATE   = "IMPORT_STATE";







export const EMPLOYEE_TYPE_LIST = "EMPLOYEE_TYPE_LIST";
export const ADD_EMPLOYEE_TYPE = "ADD_EMPLOYEE_TYPE";
export const EDIT_EMPLOYEE_TYPE = "EDIT_EMPLOYEE_TYPE";
export const DELETE_EMPLOYEE_TYPE = "DELETE_EMPLOYEE_TYPE";
export const EXPORT_EMPLOYEE_TYPE = "EXPORT_EMPLOYEE_TYPE";
export const IMPORT_EMPLOYEE_TYPE = "IMPORT_EMPLOYEE_TYPE";