// Education level code
export const EDUCATION_LEVEL_CODE_LIST = "EDUCATION_LEVEL_CODE_LIST";
export const ADD_EDUCATION_LEVEL_CODE = "ADD_EDUCATION_LEVEL_CODE";
export const EDIT_EDUCATION_LEVEL_CODE = "EDIT_EDUCATION_LEVEL_CODE";
export const DELETE_EDUCATION_LEVEL_CODE = "DELETE_EDUCATION_LEVEL_CODE";
export const EXPORT_EDUCATION_LEVEL_CODE = "EXPORT_EDUCATION_LEVEL_CODE";
export const IMPORT_EDUCATION_LEVEL_CODE = "IMPORT_EDUCATION_LEVEL_CODE";

//Education level
export const EDUCATION_LEVEL_LIST = "EDUCATION_LEVEL_LIST";
export const ADD_EDUCATION_LEVEL = "ADD_EDUCATION_LEVEL";
export const EDIT_EDUCATION_LEVEL = "EDIT_EDUCATION_LEVEL";
export const DELETE_EDUCATION_LEVEL = "DELETE_EDUCATION_LEVEL";
export const EXPORT_EDUCATION_LEVEL = "EXPORT_EDUCATION_LEVEL";
export const IMPORT_EDUCATION_LEVEL = "IMPORT_EDUCATION_LEVEL";

//Study Main Area
export const STUDY_MAIN_AREA_LIST = "STUDY_MAIN_AREA_LIST";
export const ADD_STUDY_MAIN_AREA = "ADD_STUDY_MAIN_AREA";
export const EDIT_STUDY_MAIN_AREA = "EDIT_STUDY_MAIN_AREA";
export const DELETE_STUDY_MAIN_AREA = "DELETE_STUDY_MAIN_AREA";
export const EXPORT_STUDY_MAIN_AREA = "EXPORT_STUDY_MAIN_AREA";
export const IMPORT_STUDY_MAIN_AREA = "IMPORT_STUDY_MAIN_AREA";


