// Education level code
export const EDUCATION_LEVEL_CODE_LIST = "EDUCATION_LEVEL_CODE_LIST";
export const ADD_EDUCATION_LEVEL_CODE = "ADD_EDUCATION_LEVEL_CODE";
export const EDIT_EDUCATION_LEVEL_CODE = "EDIT_EDUCATION_LEVEL_CODE";
export const DELETE_EDUCATION_LEVEL_CODE = "DELETE_EDUCATION_LEVEL_CODE";
export const EXPORT_EDUCATION_LEVEL_CODE = "EXPORT_EDUCATION_LEVEL_CODE";
export const IMPORT_EDUCATION_LEVEL_CODE = "IMPORT_EDUCATION_LEVEL_CODE";

//Education level
export const EDUCATION_LEVEL_LIST = "EDUCATION_LEVEL_LIST";
export const ADD_EDUCATION_LEVEL = "ADD_EDUCATION_LEVEL";
export const EDIT_EDUCATION_LEVEL = "EDIT_EDUCATION_LEVEL";
export const DELETE_EDUCATION_LEVEL = "DELETE_EDUCATION_LEVEL";
export const EXPORT_EDUCATION_LEVEL = "EXPORT_EDUCATION_LEVEL";
export const IMPORT_EDUCATION_LEVEL = "IMPORT_EDUCATION_LEVEL";

//Study Main Area
export const STUDY_MAIN_AREA_LIST = "STUDY_MAIN_AREA_LIST";
export const ADD_STUDY_MAIN_AREA = "ADD_STUDY_MAIN_AREA";
export const EDIT_STUDY_MAIN_AREA = "EDIT_STUDY_MAIN_AREA";
export const DELETE_STUDY_MAIN_AREA = "DELETE_STUDY_MAIN_AREA";
export const EXPORT_STUDY_MAIN_AREA = "EXPORT_STUDY_MAIN_AREA";
export const IMPORT_STUDY_MAIN_AREA = "IMPORT_STUDY_MAIN_AREA";

//Education Duration
export const EDUCATION_DURATION_LIST = "EDUCATION_DURATION_LIST";
export const ADD_EDUCATION_DURATION = "ADD_EDUCATION_DURATION";
export const EDIT_EDUCATION_DURATION = "EDIT_EDUCATION_DURATION";
export const DELETE_EDUCATION_DURATION = "DELETE_EDUCATION_DURATION";
export const EXPORT_EDUCATION_DURATION = "EXPORT_EDUCATION_DURATION";
export const IMPORT_EDUCATION_DURATION = "IMPORT_EDUCATION_DURATION";

// Study Major Area
export const STUDY_MAJOR_AREA_LIST = "STUDY_MAJOR_AREA_LIST";
export const ADD_STUDY_MAJOR_AREA = "ADD_STUDY_MAJOR_AREA";
export const EDIT_STUDY_MAJOR_AREA = "EDIT_STUDY_MAJOR_AREA";
export const DELETE_STUDY_MAJOR_AREA = "DELETE_STUDY_MAJOR_AREA";
export const EXPORT_STUDY_MAJOR_AREA = "EXPORT_STUDY_MAJOR_AREA";
export const IMPORT_STUDY_MAJOR_AREA = "IMPORT_STUDY_MAJOR_AREA";
export const STUDY_MAJOR_AREA_LIST_BY_MAIN_AREA = "STUDY_MAJOR_AREA_LIST_BY_MAIN_AREA";

// Academic Result Type
export const ACADEMIC_RESULT_TYPE_LIST = "ACADEMIC_RESULT_TYPE_LIST";
export const ADD_ACADEMIC_RESULT_TYPE = "ADD_ACADEMIC_RESULT_TYPE";
export const EDIT_ACADEMIC_RESULT_TYPE = "EDIT_ACADEMIC_RESULT_TYPE";
export const DELETE_ACADEMIC_RESULT_TYPE = "DELETE_ACADEMIC_RESULT_TYPE";
export const EXPORT_ACADEMIC_RESULT_TYPE = "EXPORT_ACADEMIC_RESULT_TYPE";
export const IMPORT_ACADEMIC_RESULT_TYPE = "IMPORT_ACADEMIC_RESULT_TYPE";
//Education Type
export const EDUCATION_TYPE_LIST = "EDUCATION_TYPE_LIST";
export const ADD_EDUCATION_TYPE = "ADD_EDUCATION_TYPE";
export const EDIT_EDUCATION_TYPE = "EDIT_EDUCATION_TYPE";
export const DELETE_EDUCATION_TYPE = "DELETE_EDUCATION_TYPE";
export const EXPORT_EDUCATION_TYPE = "EXPORT_EDUCATION_TYPE";
export const IMPORT_EDUCATION_TYPE = "IMPORT_EDUCATION_TYPE";
// Study Specialisation
export const STUDY_SPECIALISATION_LIST = "STUDY_SPECIALISATION_LIST";
export const ADD_STUDY_SPECIALISATION = "ADD_STUDY_SPECIALISATION";
export const EDIT_STUDY_SPECIALISATION = "EDIT_STUDY_SPECIALISATION";
export const DELETE_STUDY_SPECIALISATION = "DELETE_STUDY_SPECIALISATION";
export const EXPORT_STUDY_SPECIALISATION = "EXPORT_STUDY_SPECIALISATION";
export const IMPORT_STUDY_SPECIALISATION = "IMPORT_STUDY_SPECIALISATION";
// Degree awarded by
export const DEGREE_AWARDED_BY_LIST = "DEGREE_AWARDED_BY_LIST";
export const ADD_DEGREE_AWARDED_BY = "ADD_DEGREE_AWARDED_BY";
export const EDIT_DEGREE_AWARDED_BY = "EDIT_DEGREE_AWARDED_BY";
export const DELETE_DEGREE_AWARDED_BY = "DELETE_DEGREE_AWARDED_BY";
export const EXPORT_DEGREE_AWARDED_BY = "EXPORT_DEGREE_AWARDED_BY";
export const IMPORT_DEGREE_AWARDED_BY = "IMPORT_DEGREE_AWARDED_BY";
// Academin Result 
export const ACADEMIC_RESULT_LIST = "ACADEMIC_RESULT_LIST";
export const ADD_ACADEMIC_RESULT = "ADD_ACADEMIC_RESULT";
export const EDIT_ACADEMIC_RESULT = "EDIT_ACADEMIC_RESULT";
export const DELETE_ACADEMIC_RESULT = "DELETE_ACADEMIC_RESULT";
export const EXPORT_ACADEMIC_RESULT = "EXPORT_ACADEMIC_RESULT";
export const IMPORT_ACADEMIC_RESULT = "IMPORT_ACADEMIC_RESULT";
// Degree Awarded
export const DEGREE_AWARDED_INSTITUTE_LIST = "DEGREE_AWARDED_INSTITUTE_LIST";
export const ADD_DEGREE_AWARDED_INSTITUTE = "ADD_DEGREE_AWARDED_INSTITUTE";
export const EDIT_DEGREE_AWARDED_INSTITUTE = "EDIT_DEGREE_AWARDED_INSTITUTE";
export const DELETE_DEGREE_AWARDED_INSTITUTE = "DELETE_DEGREE_AWARDED_INSTITUTE";
export const EXPORT_DEGREE_AWARDED_INSTITUTE = "EXPORT_DEGREE_AWARDED_INSTITUTE";
export const IMPORT_DEGREE_AWARDED_INSTITUTE = "IMPORT_DEGREE_AWARDED_INSTITUTE";
// Academic result to result
export const ACADEMIC_RESULT_TO_RESULT_LIST = "ACADEMIC_RESULT_TO_RESULT_LIST";
export const ADD_ACADEMIC_RESULT_TO_RESULT = "ADD_ACADEMIC_RESULT_TO_RESULT";
export const EDIT_ACADEMIC_RESULT_TO_RESULT = "EDIT_ACADEMIC_RESULT_TO_RESULT";
export const DELETE_ACADEMIC_RESULT_TO_RESULT = "DELETE_ACADEMIC_RESULT_TO_RESULT";
export const EXPORT_ACADEMIC_RESULT_TO_RESULT = "EXPORT_ACADEMIC_RESULT_TO_RESULT";
export const IMPORT_ACADEMIC_RESULT_TO_RESULT = "IMPORT_ACADEMIC_RESULT_TO_RESULT";
// ECA Awarding Body
export const ECA_AWARDING_BODY_LIST = "ECA_AWARDING_BODY_LIST";
export const ADD_ECA_AWARDING_BODY = "ADD_ECA_AWARDING_BODY";
export const EDIT_ECA_AWARDING_BODY = "EDIT_ECA_AWARDING_BODY";
export const DELETE_ECA_AWARDING_BODY = "DELETE_ECA_AWARDING_BODY";
export const EXPORT_ECA_AWARDING_BODY = "EXPORT_ECA_AWARDING_BODY";
export const IMPORT_ECA_AWARDING_BODY = "IMPORT_ECA_AWARDING_BODY";
// Medium of Education
export const MEDIUM_OF_EDUCATION_LIST = "MEDIUM_OF_EDUCATION_LIST";
export const ADD_MEDIUM_OF_EDUCATION = "ADD_MEDIUM_OF_EDUCATION";
export const EDIT_MEDIUM_OF_EDUCATION = "EDIT_MEDIUM_OF_EDUCATION";
export const DELETE_MEDIUM_OF_EDUCATION = "DELETE_MEDIUM_OF_EDUCATION";
export const EXPORT_MEDIUM_OF_EDUCATION = "EXPORT_MEDIUM_OF_EDUCATION";
export const IMPORT_MEDIUM_OF_EDUCATION = "IMPORT_MEDIUM_OF_EDUCATION";
// ECA For 
export const ECA_FOR_LIST = "ECA_FOR_LIST";
export const ADD_ECA_FOR = "ADD_ECA_FOR";
export const EDIT_ECA_FOR = "EDIT_ECA_FOR";
export const DELETE_ECA_FOR = "DELETE_ECA_FOR";
export const EXPORT_ECA_FOR = "EXPORT_ECA_FOR";
export const IMPORT_ECA_FOR = "IMPORT_ECA_FOR";













