// Language Name (Test)
export const LANGUAGE_NAME_TEST_LIST = "LANGUAGE_NAME_TEST_LIST";
export const ADD_LANGUAGE_NAME_TEST = "ADD_LANGUAGE_NAME_TEST";
export const EDIT_LANGUAGE_NAME_TEST = "EDIT_LANGUAGE_NAME_TEST";
export const DELETE_LANGUAGE_NAME_TEST = "DELETE_LANGUAGE_NAME_TEST";
export const EXPORT_LANGUAGE_NAME_TEST = "EXPORT_LANGUAGE_NAME_TEST";
export const IMPORT_LANGUAGE_NAME_TEST = "IMPORT_LANGUAGE_NAME_TEST";

// Language Test Name
export const LANGUAGE_TEST_NAME_LIST = "LANGUAGE_TEST_NAME_LIST";
export const ADD_LANGUAGE_TEST_NAME = "ADD_LANGUAGE_TEST_NAME";
export const EDIT_LANGUAGE_TEST_NAME = "EDIT_LANGUAGE_TEST_NAME";
export const DELETE_LANGUAGE_TEST_NAME = "DELETE_LANGUAGE_TEST_NAME";
export const EXPORT_LANGUAGE_TEST_NAME = "EXPORT_LANGUAGE_TEST_NAME";
export const IMPORT_LANGUAGE_TEST_NAME = "IMPORT_LANGUAGE_TEST_NAME";

// Language Test Module Name
export const LANGUAGE_TEST_MODULE_NAME_LIST = "LANGUAGE_TEST_MODULE_NAME_LIST";
export const ADD_LANGUAGE_TEST_MODULE_NAME = "ADD_LANGUAGE_TEST_MODULE_NAME";
export const EDIT_LANGUAGE_TEST_MODULE_NAME = "EDIT_LANGUAGE_TEST_MODULE_NAME";
export const DELETE_LANGUAGE_TEST_MODULE_NAME = "DELETE_LANGUAGE_TEST_MODULE_NAME";
export const EXPORT_LANGUAGE_TEST_MODULE_NAME = "EXPORT_LANGUAGE_TEST_MODULE_NAME";
export const IMPORT_LANGUAGE_TEST_MODULE_NAME = "IMPORT_LANGUAGE_TEST_MODULE_NAME";

// Language Benchmark Level
export const LANGUAGE_BENCHMARK_LEVEL_LIST = "LANGUAGE_BENCHMARK_LEVEL_LIST";
export const ADD_LANGUAGE_BENCHMARK_LEVEL = "ADD_LANGUAGE_BENCHMARK_LEVEL";
export const EDIT_LANGUAGE_BENCHMARK_LEVEL = "EDIT_LANGUAGE_BENCHMARK_LEVEL";
export const DELETE_LANGUAGE_BENCHMARK_LEVEL = "DELETE_LANGUAGE_BENCHMARK_LEVEL";
export const EXPORT_LANGUAGE_BENCHMARK_LEVEL = "EXPORT_LANGUAGE_BENCHMARK_LEVEL";
export const IMPORT_LANGUAGE_BENCHMARK_LEVEL = "IMPORT_LANGUAGE_BENCHMARK_LEVEL";

// CLB Level
export const CLB_LEVEL_LIST = "CLB_LEVEL_LIST";
export const ADD_CLB_LEVEL = "ADD_CLB_LEVEL";
export const EDIT_CLB_LEVEL = "EDIT_CLB_LEVEL";
export const DELETE_CLB_LEVEL = "DELETE_CLB_LEVEL";
export const EXPORT_CLB_LEVEL = "EXPORT_CLB_LEVEL";
export const IMPORT_CLB_LEVEL = "IMPORT_CLB_LEVEL";
// Entrance Test Name
export const ENTRANCE_TEST_NAME_LIST = "ENTRANCE_TEST_NAME_LIST";
export const ADD_ENTRANCE_TEST_NAME = "ADD_ENTRANCE_TEST_NAME";
export const EDIT_ENTRANCE_TEST_NAME = "EDIT_ENTRANCE_TEST_NAME";
export const DELETE_ENTRANCE_TEST_NAME = "DELETE_ENTRANCE_TEST_NAME";
export const EXPORT_ENTRANCE_TEST_NAME = "EXPORT_ENTRANCE_TEST_NAME";
export const IMPORT_ENTRANCE_TEST_NAME = "IMPORT_ENTRANCE_TEST_NAME";

// Entrance Test Module Name
export const ENTRANCE_TEST_MODULE_NAME_LIST = "ENTRANCE_TEST_MODULE_NAME_LIST";
export const ADD_ENTRANCE_TEST_MODULE_NAME = "ADD_ENTRANCE_TEST_MODULE_NAME";
export const EDIT_ENTRANCE_TEST_MODULE_NAME = "EDIT_ENTRANCE_TEST_MODULE_NAME";
export const DELETE_ENTRANCE_TEST_MODULE_NAME = "DELETE_ENTRANCE_TEST_MODULE_NAME";
export const EXPORT_ENTRANCE_TEST_MODULE_NAME = "EXPORT_ENTRANCE_TEST_MODULE_NAME";
export const IMPORT_ENTRANCE_TEST_MODULE_NAME = "IMPORT_ENTRANCE_TEST_MODULE_NAME";
// Entrance Test Result
export const ENTRANCE_TEST_RESULT_LIST = "ENTRANCE_TEST_RESULT_LIST";
export const ADD_ENTRANCE_TEST_RESULT = "ADD_ENTRANCE_TEST_RESULT";
export const EDIT_ENTRANCE_TEST_RESULT = "EDIT_ENTRANCE_TEST_RESULT";
export const DELETE_ENTRANCE_TEST_RESULT = "DELETE_ENTRANCE_TEST_RESULT";
export const EXPORT_ENTRANCE_TEST_RESULT = "EXPORT_ENTRANCE_TEST_RESULT";
export const IMPORT_ENTRANCE_TEST_RESULT = "IMPORT_ENTRANCE_TEST_RESULT";
// Language Test Result
export const LANGUAGE_TEST_RESULT_LIST = "LANGUAGE_TEST_RESULT_LIST";
export const ADD_LANGUAGE_TEST_RESULT = "ADD_LANGUAGE_TEST_RESULT";
export const EDIT_LANGUAGE_TEST_RESULT = "EDIT_LANGUAGE_TEST_RESULT";
export const DELETE_LANGUAGE_TEST_RESULT = "DELETE_LANGUAGE_TEST_RESULT";
export const EXPORT_LANGUAGE_TEST_RESULT = "EXPORT_LANGUAGE_TEST_RESULT";
export const IMPORT_LANGUAGE_TEST_RESULT = "IMPORT_LANGUAGE_TEST_RESULT";






