// Language Name (Test)
export const LANGUAGE_NAME_TEST_LIST = "LANGUAGE_NAME_TEST_LIST";
export const ADD_LANGUAGE_NAME_TEST = "ADD_LANGUAGE_NAME_TEST";
export const EDIT_LANGUAGE_NAME_TEST = "EDIT_LANGUAGE_NAME_TEST";
export const DELETE_LANGUAGE_NAME_TEST = "DELETE_LANGUAGE_NAME_TEST";
export const EXPORT_LANGUAGE_NAME_TEST = "EXPORT_LANGUAGE_NAME_TEST";
export const IMPORT_LANGUAGE_NAME_TEST = "IMPORT_LANGUAGE_NAME_TEST";

// Language Test Name
export const LANGUAGE_TEST_NAME_LIST = "LANGUAGE_TEST_NAME_LIST";
export const ADD_LANGUAGE_TEST_NAME = "ADD_LANGUAGE_TEST_NAME";
export const EDIT_LANGUAGE_TEST_NAME = "EDIT_LANGUAGE_TEST_NAME";
export const DELETE_LANGUAGE_TEST_NAME = "DELETE_LANGUAGE_TEST_NAME";
export const EXPORT_LANGUAGE_TEST_NAME = "EXPORT_LANGUAGE_TEST_NAME";
export const IMPORT_LANGUAGE_TEST_NAME = "IMPORT_LANGUAGE_TEST_NAME";
