
// ACTIVITY_TYPE
export const ACTIVITY_TYPE_LIST = "ACTIVITY_TYPE_LIST";
export const ADD_ACTIVITY_TYPE = "ADD_ACTIVITY_TYPE";
export const EDIT_ACTIVITY_TYPE = "EDIT_ACTIVITY_TYPE";
export const DELETE_ACTIVITY_TYPE = "DELETE_ACTIVITY_TYPE";
export const EXPORT_ACTIVITY_TYPE = "EXPORT_ACTIVITY_TYPE";
export const IMPORT_ACTIVITY_TYPE = "IMPORT_ACTIVITY_TYPE";

// LOST_REASON_B2C
export const LOST_REASON_B2C_LIST = "LOST_REASON_B2C_LIST";
export const ADD_LOST_REASON_B2C = "ADD_LOST_REASON_B2C";
export const EDIT_LOST_REASON_B2C = "EDIT_LOST_REASON_B2C";
export const DELETE_LOST_REASON_B2C = "DELETE_LOST_REASON_B2C";
export const EXPORT_LOST_REASON_B2C = "EXPORT_LOST_REASON_B2C";
export const IMPORT_LOST_REASON_B2C = "IMPORT_LOST_REASON_B2C";

// LOST_REASON_B2B
export const LOST_REASON_B2B_LIST = "LOST_REASON_B2B_LIST";
export const ADD_LOST_REASON_B2B = "ADD_LOST_REASON_B2B";
export const EDIT_LOST_REASON_B2B = "EDIT_LOST_REASON_B2B";
export const DELETE_LOST_REASON_B2B = "DELETE_LOST_REASON_B2B";
export const EXPORT_LOST_REASON_B2B = "EXPORT_LOST_REASON_B2B";
export const IMPORT_LOST_REASON_B2B = "IMPORT_LOST_REASON_B2B";

// LEAD_SOURCE
export const LEAD_SOURCE_LIST = "LEAD_SOURCE_LIST";
export const ADD_LEAD_SOURCE = "ADD_LEAD_SOURCE";
export const EDIT_LEAD_SOURCE = "EDIT_LEAD_SOURCE";
export const DELETE_LEAD_SOURCE = "DELETE_LEAD_SOURCE";
export const EXPORT_LEAD_SOURCE = "EXPORT_LEAD_SOURCE";
export const IMPORT_LEAD_SOURCE = "IMPORT_LEAD_SOURCE";

// INTEREST_LEVEL
export const INTEREST_LEVEL_LIST = "INTEREST_LEVEL_LIST";
export const ADD_INTEREST_LEVEL = "ADD_INTEREST_LEVEL";
export const EDIT_INTEREST_LEVEL = "EDIT_INTEREST_LEVEL";
export const DELETE_INTEREST_LEVEL = "DELETE_INTEREST_LEVEL";
export const EXPORT_INTEREST_LEVEL = "EXPORT_INTEREST_LEVEL";
export const IMPORT_INTEREST_LEVEL = "IMPORT_INTEREST_LEVEL";