
// ACTIVITY_TYPE
export const ACTIVITY_TYPE_LIST = "ACTIVITY_TYPE_LIST";
export const ADD_ACTIVITY_TYPE = "ADD_ACTIVITY_TYPE";
export const EDIT_ACTIVITY_TYPE = "EDIT_ACTIVITY_TYPE";
export const DELETE_ACTIVITY_TYPE = "DELETE_ACTIVITY_TYPE";
export const EXPORT_ACTIVITY_TYPE = "EXPORT_ACTIVITY_TYPE";
export const IMPORT_ACTIVITY_TYPE = "IMPORT_ACTIVITY_TYPE";