
// ACTIVITY_TYPE
export const ACTIVITY_TYPE_LIST = "ACTIVITY_TYPE_LIST";
export const ADD_ACTIVITY_TYPE = "ADD_ACTIVITY_TYPE";
export const EDIT_ACTIVITY_TYPE = "EDIT_ACTIVITY_TYPE";
export const DELETE_ACTIVITY_TYPE = "DELETE_ACTIVITY_TYPE";
export const EXPORT_ACTIVITY_TYPE = "EXPORT_ACTIVITY_TYPE";
export const IMPORT_ACTIVITY_TYPE = "IMPORT_ACTIVITY_TYPE";

// LOST_REASON_B2C
export const LOST_REASON_B2C_LIST = "LOST_REASON_B2C_LIST";
export const ADD_LOST_REASON_B2C = "ADD_LOST_REASON_B2C";
export const EDIT_LOST_REASON_B2C = "EDIT_LOST_REASON_B2C";
export const DELETE_LOST_REASON_B2C = "DELETE_LOST_REASON_B2C";
export const EXPORT_LOST_REASON_B2C = "EXPORT_LOST_REASON_B2C";
export const IMPORT_LOST_REASON_B2C = "IMPORT_LOST_REASON_B2C";