

// BANK_ACCOUNT_TYPE
export const BANK_ACCOUNT_TYPE_LIST = "BANK_ACCOUNT_TYPE_LIST";
export const ADD_BANK_ACCOUNT_TYPE = "ADD_BANK_ACCOUNT_TYPE";
export const EDIT_BANK_ACCOUNT_TYPE = "EDIT_BANK_ACCOUNT_TYPE";
export const DELETE_BANK_ACCOUNT_TYPE = "DELETE_BANK_ACCOUNT_TYPE";
export const EXPORT_BANK_ACCOUNT_TYPE = "EXPORT_BANK_ACCOUNT_TYPE";
export const IMPORT_BANK_ACCOUNT_TYPE = "IMPORT_BANK_ACCOUNT_TYPE";

// STAKEHOLDER_TYPE
export const STAKEHOLDER_TYPE_LIST = "STAKEHOLDER_TYPE_LIST";
export const ADD_STAKEHOLDER_TYPE = "ADD_STAKEHOLDER_TYPE";
export const EDIT_STAKEHOLDER_TYPE = "EDIT_STAKEHOLDER_TYPE";
export const DELETE_STAKEHOLDER_TYPE = "DELETE_STAKEHOLDER_TYPE";
export const EXPORT_STAKEHOLDER_TYPE = "EXPORT_STAKEHOLDER_TYPE";
export const IMPORT_STAKEHOLDER_TYPE = "IMPORT_STAKEHOLDER_TYPE";

// OWNERSHIP_TYPE
export const OWNERSHIP_TYPE_LIST = "OWNERSHIP_TYPE_LIST";
export const ADD_OWNERSHIP_TYPE = "ADD_OWNERSHIP_TYPE";
export const EDIT_OWNERSHIP_TYPE = "EDIT_OWNERSHIP_TYPE";
export const DELETE_OWNERSHIP_TYPE = "DELETE_OWNERSHIP_TYPE";
export const EXPORT_OWNERSHIP_TYPE = "EXPORT_OWNERSHIP_TYPE";
export const IMPORT_OWNERSHIP_TYPE = "IMPORT_OWNERSHIP_TYPE";

// ACCREDITATION_CATEGORY
export const ACCREDITATION_CATEGORY_LIST = "ACCREDITATION_CATEGORY_LIST";
export const ADD_ACCREDITATION_CATEGORY = "ADD_ACCREDITATION_CATEGORY";
export const EDIT_ACCREDITATION_CATEGORY = "EDIT_ACCREDITATION_CATEGORY";
export const DELETE_ACCREDITATION_CATEGORY = "DELETE_ACCREDITATION_CATEGORY";
export const EXPORT_ACCREDITATION_CATEGORY = "EXPORT_ACCREDITATION_CATEGORY";
export const IMPORT_ACCREDITATION_CATEGORY = "IMPORT_ACCREDITATION_CATEGORY";

// LICENCE_NAME
export const LICENCE_NAME_LIST = "LICENCE_NAME_LIST";
export const ADD_LICENCE_NAME = "ADD_LICENCE_NAME";
export const EDIT_LICENCE_NAME = "EDIT_LICENCE_NAME";
export const DELETE_LICENCE_NAME = "DELETE_LICENCE_NAME";
export const EXPORT_LICENCE_NAME = "EXPORT_LICENCE_NAME";
export const IMPORT_LICENCE_NAME = "IMPORT_LICENCE_NAME";

// ACCREDITATION_NAME
export const ACCREDITATION_NAME_LIST = "ACCREDITATION_NAME_LIST";
export const ADD_ACCREDITATION_NAME = "ADD_ACCREDITATION_NAME";
export const EDIT_ACCREDITATION_NAME = "EDIT_ACCREDITATION_NAME";
export const DELETE_ACCREDITATION_NAME = "DELETE_ACCREDITATION_NAME";
export const EXPORT_ACCREDITATION_NAME = "EXPORT_ACCREDITATION_NAME";

export const COUNTRY_LIST_DEMO = "COUNTRY_LIST_DEMO";