

// BANK_ACCOUNT_TYPE
export const BANK_ACCOUNT_TYPE_LIST = "BANK_ACCOUNT_TYPE_LIST";
export const ADD_BANK_ACCOUNT_TYPE = "ADD_BANK_ACCOUNT_TYPE";
export const EDIT_BANK_ACCOUNT_TYPE = "EDIT_BANK_ACCOUNT_TYPE";
export const DELETE_BANK_ACCOUNT_TYPE = "DELETE_BANK_ACCOUNT_TYPE";
export const EXPORT_BANK_ACCOUNT_TYPE = "EXPORT_BANK_ACCOUNT_TYPE";
export const IMPORT_BANK_ACCOUNT_TYPE = "IMPORT_BANK_ACCOUNT_TYPE";

// STAKEHOLDER_TYPE
export const STAKEHOLDER_TYPE_LIST = "STAKEHOLDER_TYPE_LIST";
export const ADD_STAKEHOLDER_TYPE = "ADD_STAKEHOLDER_TYPE";
export const EDIT_STAKEHOLDER_TYPE = "EDIT_STAKEHOLDER_TYPE";
export const DELETE_STAKEHOLDER_TYPE = "DELETE_STAKEHOLDER_TYPE";
export const EXPORT_STAKEHOLDER_TYPE = "EXPORT_STAKEHOLDER_TYPE";
export const IMPORT_STAKEHOLDER_TYPE = "IMPORT_STAKEHOLDER_TYPE";

// OWNERSHIP_TYPE
export const OWNERSHIP_TYPE_LIST = "OWNERSHIP_TYPE_LIST";
export const ADD_OWNERSHIP_TYPE = "ADD_OWNERSHIP_TYPE";
export const EDIT_OWNERSHIP_TYPE = "EDIT_OWNERSHIP_TYPE";
export const DELETE_OWNERSHIP_TYPE = "DELETE_OWNERSHIP_TYPE";
export const EXPORT_OWNERSHIP_TYPE = "EXPORT_OWNERSHIP_TYPE";
export const IMPORT_OWNERSHIP_TYPE = "IMPORT_OWNERSHIP_TYPE";