

// BANK_ACCOUNT_TYPE
export const BANK_ACCOUNT_TYPE_LIST = "BANK_ACCOUNT_TYPE_LIST";
export const ADD_BANK_ACCOUNT_TYPE = "ADD_BANK_ACCOUNT_TYPE";
export const EDIT_BANK_ACCOUNT_TYPE = "EDIT_BANK_ACCOUNT_TYPE";
export const DELETE_BANK_ACCOUNT_TYPE = "DELETE_BANK_ACCOUNT_TYPE";
export const EXPORT_BANK_ACCOUNT_TYPE = "EXPORT_BANK_ACCOUNT_TYPE";
export const IMPORT_BANK_ACCOUNT_TYPE = "IMPORT_BANK_ACCOUNT_TYPE";